// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaKnsxAVluS2bY_vFeHWiachEPtaajOyU',
    appId: '1:900231571435:web:652e5c26aa4635aaac5bae',
    messagingSenderId: '900231571435',
    projectId: 'rental-a3bc9',
    authDomain: 'rental-a3bc9.firebaseapp.com',
    storageBucket: 'rental-a3bc9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgAMLf6dvKSr5PMEEeNGuOF0TAYY7dpC4',
    appId: '1:900231571435:android:446cf4986ee8184fac5bae',
    messagingSenderId: '900231571435',
    projectId: 'rental-a3bc9',
    storageBucket: 'rental-a3bc9.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaKnsxAVluS2bY_vFeHWiachEPtaajOyU',
    appId: '1:900231571435:web:cdbc10eaedf27713ac5bae',
    messagingSenderId: '900231571435',
    projectId: 'rental-a3bc9',
    authDomain: 'rental-a3bc9.firebaseapp.com',
    storageBucket: 'rental-a3bc9.appspot.com',
  );
}
